events {}

http {
  upstream auth_service {
    server auth-service:3000;
  }

  server {
    listen 443 ssl;

    ssl_certificate     /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;

    location /auth/ {
      proxy_pass http://auth_service/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}